sudo: required
services: 
  - docker

before_install: 
  - docker build -t bhoopendra/burger-builder -f burger-builder/Dockerfile.dev burger-builder/.

script: 
  - docker run bhoopendra/burger-builder npm run test -- --coverage

after_success:
  - docker build -t bhoopendra/burger-builder ./burger-builder

  #Login to the hub.docker.com using Docker Cli
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  #Push the images to hub.docker.com
  - docker push bhoopendra/burger-builder